name: Java CI

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: self-hosted

    steps:
    
    - uses: actions/checkout@v2
    
    - name: Checkout
      env:
        token: ${{ secrets.PAT }}
      run: git clone git@github.com:aws-actions/codeguru-reviewer.git

#     - name: Setup SSH Keys and known_hosts
#       env:
#         SSHK: ${{ secrets.SSH_KEY }}
#       run: |
#           mkdir -p $HOME/.ssh
#           echo "$SSHK" > $HOME/.ssh/ssh.key
#           chmod 600 $HOME/.ssh/ssh.key
#           export GIT_SSH_COMMAND="ssh -i $HOME/.ssh/ssh.key"
        
#     - uses: actions/checkout@v2
#       with:
#         repository: aws-actions/codeguru-reviewer
# #         token: ${{ secrets.PAT }}
#         ssh-key: ${{ secrets.SSH_KEY }}
#         ref: refs/heads/main
#         path: ./.github/actions/codeguru-reviewer

    - name: Setup SSH agent
      env:
        SSH_KEY: ${{ secrets.SSH_KEY }}
      run: |
        eval $(ssh-agent -s)
        echo $SSH_KEY | tr -d '\r' | ssh-add -
        mkdir -p ~/.ssh
        chmod 700 ~/.ssh 
        ssh-keyscan github.com >> ~/.ssh/known_hosts
        chmod 644 ~/.ssh/known_hosts

    - name: Checkout
      env:
        SSH_KEY: ${{ secrets.SSH_KEY }}
      run: git clone git@github.com:aws-actions/codeguru-reviewer.git
