name: Java CI

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: self-hosted

    steps:
    
    - uses: actions/checkout@v2

    - name: Setup SSH Keys and known_hosts
      env:
        SSH_AUTH_SOCK: /tmp/ssh_agent.sock
      run: |
        ssh-agent -a $SSH_AUTH_SOCK > /dev/null
        ssh-add - <<< "${{ secrets.SSH_KEY }}"
        
    - uses: actions/checkout@v2
      with:
        repository: aws-actions/codeguru-reviewer
#       token: ${{ secrets.PAT }}
        ssh-key: ${{ secrets.SSH_KEY }}
        ref: refs/heads/main
        path: ./.github/actions/codeguru-reviewer
