name: Java CI

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: self-hosted

    steps:
    
    - uses: actions/checkout@v2
    
        
    - uses: actions/checkout@v2
      with:
        repository: aws-actions/codeguru-reviewer
        ssh-key: ${{ secrets.SSH_KEY }}
        ref: refs/heads/main
        path: ./.github/actions/codeguru-reviewer
